export const COUPON_CATEGORIES = [
  { id: 'all', label: 'All Deals', icon: '🎟️' },
  { id: 'shopping', label: 'Shopping', icon: '🛍️' },
  { id: 'food', label: 'Food', icon: '🍕' },
  { id: 'grocery', label: 'Grocery', icon: '🥦' },
  { id: 'travel', label: 'Travel', icon: '✈️' },
  { id: 'pharmacy', label: 'Medicine', icon: '💊' },
  { id: 'recharge', label: 'Recharge', icon: '📱' },
  { id: 'ott', label: 'OTT', icon: '📺' },
  { id: 'bank', label: 'Bank Offers', icon: '🏦' }
];

export const allCoupons = [
  {
    "id": "c1",
    "platform": "Amazon",
    "platformCategory": "shopping",
    "platformLogo": "🛒",
    "platformColor": "#FF9900",
    "code": "AMA150",
    "title": "Flat ₹150 off on ₹300+",
    "description": "Save big with this exclusive offer from Amazon",
    "discountType": "flat",
    "discountValue": 150,
    "maxDiscount": null,
    "minOrderValue": 300,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "coupon",
    "verified": true,
    "successRate": 92,
    "lastWorked": "2 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "shopping",
      "amazon",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "shopping",
      "amazon",
      "ama150",
      "save",
      "deal"
    ],
    "aiScore": 88,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 2401
  },
  {
    "id": "c2",
    "platform": "Zomato",
    "platformCategory": "food",
    "platformLogo": "🍕",
    "platformColor": "#E23744",
    "code": "ZOM150",
    "title": "15% off up to ₹150",
    "description": "Save big with this exclusive offer from Zomato",
    "discountType": "percent",
    "discountValue": 15,
    "maxDiscount": 150,
    "minOrderValue": 600,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bank",
    "verified": true,
    "successRate": 96,
    "lastWorked": "3 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "food",
      "zomato",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "food",
      "zomato",
      "zom150",
      "save",
      "deal"
    ],
    "aiScore": 89,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 996
  },
  {
    "id": "c3",
    "platform": "BigBasket",
    "platformCategory": "grocery",
    "platformLogo": "🛒",
    "platformColor": "#84C225",
    "code": "BIG200",
    "title": "Flat ₹200 off on ₹400+",
    "description": "Save big with this exclusive offer from BigBasket",
    "discountType": "flat",
    "discountValue": 200,
    "maxDiscount": null,
    "minOrderValue": 400,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "wallet",
    "verified": true,
    "successRate": 92,
    "lastWorked": "3 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "grocery",
      "bigbasket",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "grocery",
      "bigbasket",
      "big200",
      "save",
      "deal"
    ],
    "aiScore": 91,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 1770
  },
  {
    "id": "c4",
    "platform": "Cleartrip",
    "platformCategory": "travel",
    "platformLogo": "🌍",
    "platformColor": "#F77728",
    "code": "CLE100",
    "title": "10% off up to ₹100",
    "description": "Save big with this exclusive offer from Cleartrip",
    "discountType": "percent",
    "discountValue": 10,
    "maxDiscount": 100,
    "minOrderValue": 200,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "cashback",
    "verified": true,
    "successRate": 86,
    "lastWorked": "8 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "travel",
      "cleartrip",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "travel",
      "cleartrip",
      "cle100",
      "save",
      "deal"
    ],
    "aiScore": 86,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 4112
  },
  {
    "id": "c5",
    "platform": "Tata 1mg",
    "platformCategory": "pharmacy",
    "platformLogo": "💊",
    "platformColor": "#FF6F61",
    "code": "TAT200",
    "title": "20% off up to ₹200",
    "description": "Save big with this exclusive offer from Tata 1mg",
    "discountType": "percent",
    "discountValue": 20,
    "maxDiscount": 200,
    "minOrderValue": 800,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "emi",
    "verified": true,
    "successRate": 85,
    "lastWorked": "7 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "pharmacy",
      "tata 1mg",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "pharmacy",
      "tata 1mg",
      "tat200",
      "save",
      "deal"
    ],
    "aiScore": 81,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 776
  },
  {
    "id": "c6",
    "platform": "Mobikwik",
    "platformCategory": "recharge",
    "platformLogo": "👛",
    "platformColor": "#002970",
    "code": "MOB150",
    "title": "Flat ₹150 off on ₹300+",
    "description": "Save big with this exclusive offer from Mobikwik",
    "discountType": "flat",
    "discountValue": 150,
    "maxDiscount": null,
    "minOrderValue": 300,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bogo",
    "verified": true,
    "successRate": 92,
    "lastWorked": "6 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "recharge",
      "mobikwik",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "recharge",
      "mobikwik",
      "mob150",
      "save",
      "deal"
    ],
    "aiScore": 97,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 1938
  },
  {
    "id": "c7",
    "platform": "Netflix",
    "platformCategory": "ott",
    "platformLogo": "🎬",
    "platformColor": "#E50914",
    "code": null,
    "title": "10% off up to ₹100",
    "description": "Save big with this exclusive offer from Netflix",
    "discountType": "percent",
    "discountValue": 10,
    "maxDiscount": 100,
    "minOrderValue": 200,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "sale",
    "verified": true,
    "successRate": 95,
    "lastWorked": "4 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "ott",
      "netflix",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "ott",
      "netflix",
      "net100",
      "save",
      "deal"
    ],
    "aiScore": 86,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 2168
  },
  {
    "id": "c8",
    "platform": "SBI Card",
    "platformCategory": "bank",
    "platformLogo": "💳",
    "platformColor": "#284FB5",
    "code": "SBI100",
    "title": "10% off up to ₹100",
    "description": "Save big with this exclusive offer from SBI Card",
    "discountType": "percent",
    "discountValue": 10,
    "maxDiscount": 100,
    "minOrderValue": 300,
    "cashback": 0,
    "bankOffer": "SBI Card Credit Card",
    "offerType": "coupon",
    "verified": true,
    "successRate": 95,
    "lastWorked": "5 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "bank",
      "sbi card",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "bank",
      "sbi card",
      "sbi100",
      "save",
      "deal"
    ],
    "aiScore": 88,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 2022
  },
  {
    "id": "c9",
    "platform": "Paytm",
    "platformCategory": "wallet",
    "platformLogo": "💸",
    "platformColor": "#00B9F5",
    "code": "PAY400",
    "title": "Flat ₹400 off on ₹800+",
    "description": "Save big with this exclusive offer from Paytm",
    "discountType": "flat",
    "discountValue": 400,
    "maxDiscount": null,
    "minOrderValue": 800,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bank",
    "verified": true,
    "successRate": 97,
    "lastWorked": "6 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "wallet",
      "paytm",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "wallet",
      "paytm",
      "pay400",
      "save",
      "deal"
    ],
    "aiScore": 90,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 459
  },
  {
    "id": "c10",
    "platform": "FirstCry",
    "platformCategory": "shopping",
    "platformLogo": "👶",
    "platformColor": "#FF7043",
    "code": "FIR100",
    "title": "Flat ₹100 off on ₹200+",
    "description": "Save big with this exclusive offer from FirstCry",
    "discountType": "flat",
    "discountValue": 100,
    "maxDiscount": null,
    "minOrderValue": 200,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "wallet",
    "verified": true,
    "successRate": 89,
    "lastWorked": "6 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "shopping",
      "firstcry",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "shopping",
      "firstcry",
      "fir100",
      "save",
      "deal"
    ],
    "aiScore": 90,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 752
  },
  {
    "id": "c11",
    "platform": "Dominos",
    "platformCategory": "food",
    "platformLogo": "🍕",
    "platformColor": "#0055A5",
    "code": "DOM350",
    "title": "35% off up to ₹350",
    "description": "Save big with this exclusive offer from Dominos",
    "discountType": "percent",
    "discountValue": 35,
    "maxDiscount": 350,
    "minOrderValue": 1750,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "cashback",
    "verified": true,
    "successRate": 85,
    "lastWorked": "7 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "food",
      "dominos",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "food",
      "dominos",
      "dom350",
      "save",
      "deal"
    ],
    "aiScore": 84,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 2079
  },
  {
    "id": "c12",
    "platform": "Zepto",
    "platformCategory": "grocery",
    "platformLogo": "⏱️",
    "platformColor": "#3A1847",
    "code": null,
    "title": "15% off up to ₹150",
    "description": "Save big with this exclusive offer from Zepto",
    "discountType": "percent",
    "discountValue": 15,
    "maxDiscount": 150,
    "minOrderValue": 600,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "emi",
    "verified": true,
    "successRate": 83,
    "lastWorked": "3 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "grocery",
      "zepto",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "grocery",
      "zepto",
      "zep150",
      "save",
      "deal"
    ],
    "aiScore": 96,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 219
  },
  {
    "id": "c13",
    "platform": "OYO",
    "platformCategory": "travel",
    "platformLogo": "🏨",
    "platformColor": "#EE2A24",
    "code": "OYO400",
    "title": "40% off up to ₹400",
    "description": "Save big with this exclusive offer from OYO",
    "discountType": "percent",
    "discountValue": 40,
    "maxDiscount": 400,
    "minOrderValue": 800,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "bogo",
    "verified": true,
    "successRate": 84,
    "lastWorked": "10 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "travel",
      "oyo",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "travel",
      "oyo",
      "oyo400",
      "save",
      "deal"
    ],
    "aiScore": 90,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 163
  },
  {
    "id": "c14",
    "platform": "PharmEasy",
    "platformCategory": "pharmacy",
    "platformLogo": "⚕️",
    "platformColor": "#10847E",
    "code": "PHA500",
    "title": "Flat ₹500 off on ₹1000+",
    "description": "Save big with this exclusive offer from PharmEasy",
    "discountType": "flat",
    "discountValue": 500,
    "maxDiscount": null,
    "minOrderValue": 1000,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "sale",
    "verified": true,
    "successRate": 89,
    "lastWorked": "3 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "pharmacy",
      "pharmeasy",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "pharmacy",
      "pharmeasy",
      "pha500",
      "save",
      "deal"
    ],
    "aiScore": 88,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 4364
  },
  {
    "id": "c15",
    "platform": "Google Pay",
    "platformCategory": "recharge",
    "platformLogo": "💳",
    "platformColor": "#34A853",
    "code": "GOO500",
    "title": "50% off up to ₹500",
    "description": "Save big with this exclusive offer from Google Pay",
    "discountType": "percent",
    "discountValue": 50,
    "maxDiscount": 500,
    "minOrderValue": 2000,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "coupon",
    "verified": true,
    "successRate": 99,
    "lastWorked": "9 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "recharge",
      "google pay",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "recharge",
      "google pay",
      "goo500",
      "save",
      "deal"
    ],
    "aiScore": 90,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 3343
  },
  {
    "id": "c16",
    "platform": "SonyLIV",
    "platformCategory": "ott",
    "platformLogo": "📺",
    "platformColor": "#000000",
    "code": "SON300",
    "title": "30% off up to ₹300",
    "description": "Save big with this exclusive offer from SonyLIV",
    "discountType": "percent",
    "discountValue": 30,
    "maxDiscount": 300,
    "minOrderValue": 1200,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bank",
    "verified": true,
    "successRate": 91,
    "lastWorked": "9 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "ott",
      "sonyliv",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "ott",
      "sonyliv",
      "son300",
      "save",
      "deal"
    ],
    "aiScore": 81,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 2032
  },
  {
    "id": "c17",
    "platform": "Kotak",
    "platformCategory": "bank",
    "platformLogo": "🏦",
    "platformColor": "#ED1C24",
    "code": "KOT250",
    "title": "25% off up to ₹250",
    "description": "Save big with this exclusive offer from Kotak",
    "discountType": "percent",
    "discountValue": 25,
    "maxDiscount": 250,
    "minOrderValue": 1250,
    "cashback": 0,
    "bankOffer": "Kotak Credit Card",
    "offerType": "wallet",
    "verified": true,
    "successRate": 89,
    "lastWorked": "9 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "bank",
      "kotak",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "bank",
      "kotak",
      "kot250",
      "save",
      "deal"
    ],
    "aiScore": 83,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 3984
  },
  {
    "id": "c18",
    "platform": "Paytm",
    "platformCategory": "wallet",
    "platformLogo": "💸",
    "platformColor": "#00B9F5",
    "code": "PAY500",
    "title": "Flat ₹500 off on ₹1000+",
    "description": "Save big with this exclusive offer from Paytm",
    "discountType": "flat",
    "discountValue": 500,
    "maxDiscount": null,
    "minOrderValue": 1000,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "cashback",
    "verified": true,
    "successRate": 86,
    "lastWorked": "2 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "wallet",
      "paytm",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "wallet",
      "paytm",
      "pay500",
      "save",
      "deal"
    ],
    "aiScore": 96,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 934
  },
  {
    "id": "c19",
    "platform": "Croma",
    "platformCategory": "shopping",
    "platformLogo": "🔌",
    "platformColor": "#00E9C5",
    "code": "CRO400",
    "title": "40% off up to ₹400",
    "description": "Save big with this exclusive offer from Croma",
    "discountType": "percent",
    "discountValue": 40,
    "maxDiscount": 400,
    "minOrderValue": 1600,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "emi",
    "verified": true,
    "successRate": 99,
    "lastWorked": "3 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "shopping",
      "croma",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "shopping",
      "croma",
      "cro400",
      "save",
      "deal"
    ],
    "aiScore": 94,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 168
  },
  {
    "id": "c20",
    "platform": "Pizza Hut",
    "platformCategory": "food",
    "platformLogo": "🍕",
    "platformColor": "#C8102E",
    "code": "PIZ250",
    "title": "Flat ₹250 off on ₹500+",
    "description": "Save big with this exclusive offer from Pizza Hut",
    "discountType": "flat",
    "discountValue": 250,
    "maxDiscount": null,
    "minOrderValue": 500,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bogo",
    "verified": true,
    "successRate": 85,
    "lastWorked": "9 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "food",
      "pizza hut",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "food",
      "pizza hut",
      "piz250",
      "save",
      "deal"
    ],
    "aiScore": 87,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 1347
  },
  {
    "id": "c21",
    "platform": "Blinkit",
    "platformCategory": "grocery",
    "platformLogo": "⚡",
    "platformColor": "#F8CB46",
    "code": "BLI50",
    "title": "Flat ₹50 off on ₹100+",
    "description": "Save big with this exclusive offer from Blinkit",
    "discountType": "flat",
    "discountValue": 50,
    "maxDiscount": null,
    "minOrderValue": 100,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "sale",
    "verified": true,
    "successRate": 84,
    "lastWorked": "1 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "grocery",
      "blinkit",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "grocery",
      "blinkit",
      "bli50",
      "save",
      "deal"
    ],
    "aiScore": 95,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 1358
  },
  {
    "id": "c22",
    "platform": "Agoda",
    "platformCategory": "travel",
    "platformLogo": "🗺️",
    "platformColor": "#5B99C2",
    "code": null,
    "title": "45% off up to ₹450",
    "description": "Save big with this exclusive offer from Agoda",
    "discountType": "percent",
    "discountValue": 45,
    "maxDiscount": 450,
    "minOrderValue": 2700,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "coupon",
    "verified": true,
    "successRate": 95,
    "lastWorked": "4 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "travel",
      "agoda",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "travel",
      "agoda",
      "ago450",
      "save",
      "deal"
    ],
    "aiScore": 97,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 2224
  },
  {
    "id": "c23",
    "platform": "Netmeds",
    "platformCategory": "pharmacy",
    "platformLogo": "🩺",
    "platformColor": "#32AEB1",
    "code": "NET250",
    "title": "Flat ₹250 off on ₹500+",
    "description": "Save big with this exclusive offer from Netmeds",
    "discountType": "flat",
    "discountValue": 250,
    "maxDiscount": null,
    "minOrderValue": 500,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bank",
    "verified": true,
    "successRate": 87,
    "lastWorked": "6 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "pharmacy",
      "netmeds",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "pharmacy",
      "netmeds",
      "net250",
      "save",
      "deal"
    ],
    "aiScore": 84,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 4434
  },
  {
    "id": "c24",
    "platform": "Mobikwik",
    "platformCategory": "recharge",
    "platformLogo": "👛",
    "platformColor": "#002970",
    "code": null,
    "title": "35% off up to ₹350",
    "description": "Save big with this exclusive offer from Mobikwik",
    "discountType": "percent",
    "discountValue": 35,
    "maxDiscount": 350,
    "minOrderValue": 1750,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "wallet",
    "verified": true,
    "successRate": 88,
    "lastWorked": "7 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "recharge",
      "mobikwik",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "recharge",
      "mobikwik",
      "mob350",
      "save",
      "deal"
    ],
    "aiScore": 90,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 467
  },
  {
    "id": "c25",
    "platform": "Netflix",
    "platformCategory": "ott",
    "platformLogo": "🎬",
    "platformColor": "#E50914",
    "code": "NET300",
    "title": "30% off up to ₹300",
    "description": "Save big with this exclusive offer from Netflix",
    "discountType": "percent",
    "discountValue": 30,
    "maxDiscount": 300,
    "minOrderValue": 900,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "cashback",
    "verified": true,
    "successRate": 90,
    "lastWorked": "4 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "ott",
      "netflix",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "ott",
      "netflix",
      "net300",
      "save",
      "deal"
    ],
    "aiScore": 91,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 1634
  },
  {
    "id": "c26",
    "platform": "SBI Card",
    "platformCategory": "bank",
    "platformLogo": "💳",
    "platformColor": "#284FB5",
    "code": "SBI50",
    "title": "5% off up to ₹50",
    "description": "Save big with this exclusive offer from SBI Card",
    "discountType": "percent",
    "discountValue": 5,
    "maxDiscount": 50,
    "minOrderValue": 250,
    "cashback": 0,
    "bankOffer": "SBI Card Credit Card",
    "offerType": "emi",
    "verified": true,
    "successRate": 89,
    "lastWorked": "3 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "bank",
      "sbi card",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "bank",
      "sbi card",
      "sbi50",
      "save",
      "deal"
    ],
    "aiScore": 80,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 2829
  },
  {
    "id": "c27",
    "platform": "Paytm",
    "platformCategory": "wallet",
    "platformLogo": "💸",
    "platformColor": "#00B9F5",
    "code": "PAY250",
    "title": "Flat ₹250 off on ₹500+",
    "description": "Save big with this exclusive offer from Paytm",
    "discountType": "flat",
    "discountValue": 250,
    "maxDiscount": null,
    "minOrderValue": 500,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bogo",
    "verified": true,
    "successRate": 96,
    "lastWorked": "9 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "wallet",
      "paytm",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "wallet",
      "paytm",
      "pay250",
      "save",
      "deal"
    ],
    "aiScore": 97,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 3679
  },
  {
    "id": "c28",
    "platform": "Reliance Digital",
    "platformCategory": "shopping",
    "platformLogo": "💻",
    "platformColor": "#E42529",
    "code": "REL450",
    "title": "45% off up to ₹450",
    "description": "Save big with this exclusive offer from Reliance Digital",
    "discountType": "percent",
    "discountValue": 45,
    "maxDiscount": 450,
    "minOrderValue": 2700,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "sale",
    "verified": true,
    "successRate": 95,
    "lastWorked": "8 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "shopping",
      "reliance digital",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "shopping",
      "reliance digital",
      "rel450",
      "save",
      "deal"
    ],
    "aiScore": 94,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 668
  },
  {
    "id": "c29",
    "platform": "McDonalds",
    "platformCategory": "food",
    "platformLogo": "🍟",
    "platformColor": "#FFC72C",
    "code": "MCD100",
    "title": "10% off up to ₹100",
    "description": "Save big with this exclusive offer from McDonalds",
    "discountType": "percent",
    "discountValue": 10,
    "maxDiscount": 100,
    "minOrderValue": 400,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "coupon",
    "verified": true,
    "successRate": 98,
    "lastWorked": "3 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "food",
      "mcdonalds",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "food",
      "mcdonalds",
      "mcd100",
      "save",
      "deal"
    ],
    "aiScore": 92,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 1750
  },
  {
    "id": "c30",
    "platform": "JioMart",
    "platformCategory": "grocery",
    "platformLogo": "🧺",
    "platformColor": "#0088CC",
    "code": null,
    "title": "Flat ₹150 off on ₹300+",
    "description": "Save big with this exclusive offer from JioMart",
    "discountType": "flat",
    "discountValue": 150,
    "maxDiscount": null,
    "minOrderValue": 300,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "bank",
    "verified": true,
    "successRate": 91,
    "lastWorked": "10 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "grocery",
      "jiomart",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "grocery",
      "jiomart",
      "jio150",
      "save",
      "deal"
    ],
    "aiScore": 94,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 2987
  },
  {
    "id": "c31",
    "platform": "ixigo",
    "platformCategory": "travel",
    "platformLogo": "🚆",
    "platformColor": "#2F1F83",
    "code": null,
    "title": "Flat ₹200 off on ₹400+",
    "description": "Save big with this exclusive offer from ixigo",
    "discountType": "flat",
    "discountValue": 200,
    "maxDiscount": null,
    "minOrderValue": 400,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "wallet",
    "verified": true,
    "successRate": 88,
    "lastWorked": "6 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "travel",
      "ixigo",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "travel",
      "ixigo",
      "ixi200",
      "save",
      "deal"
    ],
    "aiScore": 95,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 433
  },
  {
    "id": "c32",
    "platform": "Apollo Pharmacy",
    "platformCategory": "pharmacy",
    "platformLogo": "🏥",
    "platformColor": "#005B82",
    "code": "APO150",
    "title": "15% off up to ₹150",
    "description": "Save big with this exclusive offer from Apollo Pharmacy",
    "discountType": "percent",
    "discountValue": 15,
    "maxDiscount": 150,
    "minOrderValue": 450,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "cashback",
    "verified": true,
    "successRate": 94,
    "lastWorked": "3 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "pharmacy",
      "apollo pharmacy",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "pharmacy",
      "apollo pharmacy",
      "apo150",
      "save",
      "deal"
    ],
    "aiScore": 93,
    "isAutoApply": true,
    "isExclusive": true,
    "usedCount": 4946
  },
  {
    "id": "c33",
    "platform": "Google Pay",
    "platformCategory": "recharge",
    "platformLogo": "💳",
    "platformColor": "#34A853",
    "code": "GOO250",
    "title": "Flat ₹250 off on ₹500+",
    "description": "Save big with this exclusive offer from Google Pay",
    "discountType": "flat",
    "discountValue": 250,
    "maxDiscount": null,
    "minOrderValue": 500,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "emi",
    "verified": true,
    "successRate": 95,
    "lastWorked": "7 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "recharge",
      "google pay",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "recharge",
      "google pay",
      "goo250",
      "save",
      "deal"
    ],
    "aiScore": 99,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 4978
  },
  {
    "id": "c34",
    "platform": "SonyLIV",
    "platformCategory": "ott",
    "platformLogo": "📺",
    "platformColor": "#000000",
    "code": "SON500",
    "title": "50% off up to ₹500",
    "description": "Save big with this exclusive offer from SonyLIV",
    "discountType": "percent",
    "discountValue": 50,
    "maxDiscount": 500,
    "minOrderValue": 1000,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bogo",
    "verified": true,
    "successRate": 87,
    "lastWorked": "7 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "ott",
      "sonyliv",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "ott",
      "sonyliv",
      "son500",
      "save",
      "deal"
    ],
    "aiScore": 86,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 2153
  },
  {
    "id": "c35",
    "platform": "Kotak",
    "platformCategory": "bank",
    "platformLogo": "🏦",
    "platformColor": "#ED1C24",
    "code": "KOT400",
    "title": "Flat ₹400 off on ₹800+",
    "description": "Save big with this exclusive offer from Kotak",
    "discountType": "flat",
    "discountValue": 400,
    "maxDiscount": null,
    "minOrderValue": 800,
    "cashback": 0,
    "bankOffer": "Kotak Credit Card",
    "offerType": "sale",
    "verified": true,
    "successRate": 99,
    "lastWorked": "10 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "bank",
      "kotak",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "bank",
      "kotak",
      "kot400",
      "save",
      "deal"
    ],
    "aiScore": 89,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 3858
  },
  {
    "id": "c36",
    "platform": "Paytm",
    "platformCategory": "wallet",
    "platformLogo": "💸",
    "platformColor": "#00B9F5",
    "code": "PAY150",
    "title": "15% off up to ₹150",
    "description": "Save big with this exclusive offer from Paytm",
    "discountType": "percent",
    "discountValue": 15,
    "maxDiscount": 150,
    "minOrderValue": 450,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "coupon",
    "verified": true,
    "successRate": 91,
    "lastWorked": "6 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "wallet",
      "paytm",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "wallet",
      "paytm",
      "pay150",
      "save",
      "deal"
    ],
    "aiScore": 89,
    "isAutoApply": true,
    "isExclusive": true,
    "usedCount": 1125
  },
  {
    "id": "c37",
    "platform": "Meesho",
    "platformCategory": "shopping",
    "platformLogo": "👕",
    "platformColor": "#F43397",
    "code": "MEE250",
    "title": "25% off up to ₹250",
    "description": "Save big with this exclusive offer from Meesho",
    "discountType": "percent",
    "discountValue": 25,
    "maxDiscount": 250,
    "minOrderValue": 1500,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bank",
    "verified": true,
    "successRate": 99,
    "lastWorked": "9 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "shopping",
      "meesho",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "shopping",
      "meesho",
      "mee250",
      "save",
      "deal"
    ],
    "aiScore": 97,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 1891
  },
  {
    "id": "c38",
    "platform": "KFC",
    "platformCategory": "food",
    "platformLogo": "🍗",
    "platformColor": "#E4002B",
    "code": "KFC300",
    "title": "30% off up to ₹300",
    "description": "Save big with this exclusive offer from KFC",
    "discountType": "percent",
    "discountValue": 30,
    "maxDiscount": 300,
    "minOrderValue": 600,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "wallet",
    "verified": true,
    "successRate": 89,
    "lastWorked": "9 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "food",
      "kfc",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "food",
      "kfc",
      "kfc300",
      "save",
      "deal"
    ],
    "aiScore": 94,
    "isAutoApply": true,
    "isExclusive": true,
    "usedCount": 113
  },
  {
    "id": "c39",
    "platform": "Instamart",
    "platformCategory": "grocery",
    "platformLogo": "🥑",
    "platformColor": "#FC8019",
    "code": "INS50",
    "title": "5% off up to ₹50",
    "description": "Save big with this exclusive offer from Instamart",
    "discountType": "percent",
    "discountValue": 5,
    "maxDiscount": 50,
    "minOrderValue": 200,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "cashback",
    "verified": true,
    "successRate": 91,
    "lastWorked": "5 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "grocery",
      "instamart",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "grocery",
      "instamart",
      "ins50",
      "save",
      "deal"
    ],
    "aiScore": 82,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 1920
  },
  {
    "id": "c40",
    "platform": "Yatra",
    "platformCategory": "travel",
    "platformLogo": "✈️",
    "platformColor": "#EA2330",
    "code": "YAT200",
    "title": "Flat ₹200 off on ₹400+",
    "description": "Save big with this exclusive offer from Yatra",
    "discountType": "flat",
    "discountValue": 200,
    "maxDiscount": null,
    "minOrderValue": 400,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "emi",
    "verified": true,
    "successRate": 90,
    "lastWorked": "4 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "travel",
      "yatra",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "travel",
      "yatra",
      "yat200",
      "save",
      "deal"
    ],
    "aiScore": 88,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 693
  },
  {
    "id": "c41",
    "platform": "Tata 1mg",
    "platformCategory": "pharmacy",
    "platformLogo": "💊",
    "platformColor": "#FF6F61",
    "code": "TAT250",
    "title": "25% off up to ₹250",
    "description": "Save big with this exclusive offer from Tata 1mg",
    "discountType": "percent",
    "discountValue": 25,
    "maxDiscount": 250,
    "minOrderValue": 500,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bogo",
    "verified": true,
    "successRate": 98,
    "lastWorked": "4 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "pharmacy",
      "tata 1mg",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "pharmacy",
      "tata 1mg",
      "tat250",
      "save",
      "deal"
    ],
    "aiScore": 99,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 883
  },
  {
    "id": "c42",
    "platform": "Mobikwik",
    "platformCategory": "recharge",
    "platformLogo": "👛",
    "platformColor": "#002970",
    "code": "MOB400",
    "title": "40% off up to ₹400",
    "description": "Save big with this exclusive offer from Mobikwik",
    "discountType": "percent",
    "discountValue": 40,
    "maxDiscount": 400,
    "minOrderValue": 800,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "sale",
    "verified": true,
    "successRate": 91,
    "lastWorked": "5 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "recharge",
      "mobikwik",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "recharge",
      "mobikwik",
      "mob400",
      "save",
      "deal"
    ],
    "aiScore": 97,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 1439
  },
  {
    "id": "c43",
    "platform": "Netflix",
    "platformCategory": "ott",
    "platformLogo": "🎬",
    "platformColor": "#E50914",
    "code": null,
    "title": "Flat ₹350 off on ₹700+",
    "description": "Save big with this exclusive offer from Netflix",
    "discountType": "flat",
    "discountValue": 350,
    "maxDiscount": null,
    "minOrderValue": 700,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "coupon",
    "verified": true,
    "successRate": 90,
    "lastWorked": "7 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "ott",
      "netflix",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "ott",
      "netflix",
      "net350",
      "save",
      "deal"
    ],
    "aiScore": 92,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 1854
  },
  {
    "id": "c44",
    "platform": "SBI Card",
    "platformCategory": "bank",
    "platformLogo": "💳",
    "platformColor": "#284FB5",
    "code": "SBI50",
    "title": "5% off up to ₹50",
    "description": "Save big with this exclusive offer from SBI Card",
    "discountType": "percent",
    "discountValue": 5,
    "maxDiscount": 50,
    "minOrderValue": 250,
    "cashback": 0,
    "bankOffer": "SBI Card Credit Card",
    "offerType": "bank",
    "verified": true,
    "successRate": 80,
    "lastWorked": "9 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "bank",
      "sbi card",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "bank",
      "sbi card",
      "sbi50",
      "save",
      "deal"
    ],
    "aiScore": 82,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 1225
  },
  {
    "id": "c45",
    "platform": "Paytm",
    "platformCategory": "wallet",
    "platformLogo": "💸",
    "platformColor": "#00B9F5",
    "code": "PAY300",
    "title": "30% off up to ₹300",
    "description": "Save big with this exclusive offer from Paytm",
    "discountType": "percent",
    "discountValue": 30,
    "maxDiscount": 300,
    "minOrderValue": 1800,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "wallet",
    "verified": true,
    "successRate": 81,
    "lastWorked": "9 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "wallet",
      "paytm",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "wallet",
      "paytm",
      "pay300",
      "save",
      "deal"
    ],
    "aiScore": 92,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 4092
  },
  {
    "id": "c46",
    "platform": "Tata CLiQ",
    "platformCategory": "shopping",
    "platformLogo": "📱",
    "platformColor": "#212121",
    "code": "TAT150",
    "title": "Flat ₹150 off on ₹300+",
    "description": "Save big with this exclusive offer from Tata CLiQ",
    "discountType": "flat",
    "discountValue": 150,
    "maxDiscount": null,
    "minOrderValue": 300,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "cashback",
    "verified": true,
    "successRate": 89,
    "lastWorked": "9 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "shopping",
      "tata cliq",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "shopping",
      "tata cliq",
      "tat150",
      "save",
      "deal"
    ],
    "aiScore": 80,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 417
  },
  {
    "id": "c47",
    "platform": "Burger King",
    "platformCategory": "food",
    "platformLogo": "🍔",
    "platformColor": "#D62300",
    "code": null,
    "title": "Flat ₹150 off on ₹300+",
    "description": "Save big with this exclusive offer from Burger King",
    "discountType": "flat",
    "discountValue": 150,
    "maxDiscount": null,
    "minOrderValue": 300,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "emi",
    "verified": true,
    "successRate": 92,
    "lastWorked": "4 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "food",
      "burger king",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "food",
      "burger king",
      "bur150",
      "save",
      "deal"
    ],
    "aiScore": 99,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 1372
  },
  {
    "id": "c48",
    "platform": "BigBasket",
    "platformCategory": "grocery",
    "platformLogo": "🛒",
    "platformColor": "#84C225",
    "code": "BIG350",
    "title": "Flat ₹350 off on ₹700+",
    "description": "Save big with this exclusive offer from BigBasket",
    "discountType": "flat",
    "discountValue": 350,
    "maxDiscount": null,
    "minOrderValue": 700,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bogo",
    "verified": true,
    "successRate": 80,
    "lastWorked": "9 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "grocery",
      "bigbasket",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "grocery",
      "bigbasket",
      "big350",
      "save",
      "deal"
    ],
    "aiScore": 93,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 291
  },
  {
    "id": "c49",
    "platform": "MakeMyTrip",
    "platformCategory": "travel",
    "platformLogo": "✈️",
    "platformColor": "#D0021B",
    "code": "MAK250",
    "title": "Flat ₹250 off on ₹500+",
    "description": "Save big with this exclusive offer from MakeMyTrip",
    "discountType": "flat",
    "discountValue": 250,
    "maxDiscount": null,
    "minOrderValue": 500,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "sale",
    "verified": true,
    "successRate": 96,
    "lastWorked": "5 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "travel",
      "makemytrip",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "travel",
      "makemytrip",
      "mak250",
      "save",
      "deal"
    ],
    "aiScore": 90,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 3983
  },
  {
    "id": "c50",
    "platform": "PharmEasy",
    "platformCategory": "pharmacy",
    "platformLogo": "⚕️",
    "platformColor": "#10847E",
    "code": "PHA400",
    "title": "Flat ₹400 off on ₹800+",
    "description": "Save big with this exclusive offer from PharmEasy",
    "discountType": "flat",
    "discountValue": 400,
    "maxDiscount": null,
    "minOrderValue": 800,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "coupon",
    "verified": true,
    "successRate": 92,
    "lastWorked": "10 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "pharmacy",
      "pharmeasy",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "pharmacy",
      "pharmeasy",
      "pha400",
      "save",
      "deal"
    ],
    "aiScore": 84,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 3960
  },
  {
    "id": "c51",
    "platform": "Google Pay",
    "platformCategory": "recharge",
    "platformLogo": "💳",
    "platformColor": "#34A853",
    "code": null,
    "title": "40% off up to ₹400",
    "description": "Save big with this exclusive offer from Google Pay",
    "discountType": "percent",
    "discountValue": 40,
    "maxDiscount": 400,
    "minOrderValue": 1600,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bank",
    "verified": true,
    "successRate": 95,
    "lastWorked": "10 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "recharge",
      "google pay",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "recharge",
      "google pay",
      "goo400",
      "save",
      "deal"
    ],
    "aiScore": 91,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 2763
  },
  {
    "id": "c52",
    "platform": "SonyLIV",
    "platformCategory": "ott",
    "platformLogo": "📺",
    "platformColor": "#000000",
    "code": "SON450",
    "title": "Flat ₹450 off on ₹900+",
    "description": "Save big with this exclusive offer from SonyLIV",
    "discountType": "flat",
    "discountValue": 450,
    "maxDiscount": null,
    "minOrderValue": 900,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "wallet",
    "verified": true,
    "successRate": 99,
    "lastWorked": "7 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "ott",
      "sonyliv",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "ott",
      "sonyliv",
      "son450",
      "save",
      "deal"
    ],
    "aiScore": 94,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 3936
  },
  {
    "id": "c53",
    "platform": "Kotak",
    "platformCategory": "bank",
    "platformLogo": "🏦",
    "platformColor": "#ED1C24",
    "code": "KOT300",
    "title": "Flat ₹300 off on ₹600+",
    "description": "Save big with this exclusive offer from Kotak",
    "discountType": "flat",
    "discountValue": 300,
    "maxDiscount": null,
    "minOrderValue": 600,
    "cashback": 0,
    "bankOffer": "Kotak Credit Card",
    "offerType": "cashback",
    "verified": true,
    "successRate": 98,
    "lastWorked": "3 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "bank",
      "kotak",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "bank",
      "kotak",
      "kot300",
      "save",
      "deal"
    ],
    "aiScore": 92,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 1498
  },
  {
    "id": "c54",
    "platform": "Paytm",
    "platformCategory": "wallet",
    "platformLogo": "💸",
    "platformColor": "#00B9F5",
    "code": "PAY350",
    "title": "35% off up to ₹350",
    "description": "Save big with this exclusive offer from Paytm",
    "discountType": "percent",
    "discountValue": 35,
    "maxDiscount": 350,
    "minOrderValue": 700,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "emi",
    "verified": true,
    "successRate": 82,
    "lastWorked": "10 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "wallet",
      "paytm",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "wallet",
      "paytm",
      "pay350",
      "save",
      "deal"
    ],
    "aiScore": 85,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 4519
  },
  {
    "id": "c55",
    "platform": "Nykaa",
    "platformCategory": "shopping",
    "platformLogo": "💄",
    "platformColor": "#FC2779",
    "code": null,
    "title": "50% off up to ₹500",
    "description": "Save big with this exclusive offer from Nykaa",
    "discountType": "percent",
    "discountValue": 50,
    "maxDiscount": 500,
    "minOrderValue": 2500,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bogo",
    "verified": true,
    "successRate": 83,
    "lastWorked": "8 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "shopping",
      "nykaa",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "shopping",
      "nykaa",
      "nyk500",
      "save",
      "deal"
    ],
    "aiScore": 80,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 4803
  },
  {
    "id": "c56",
    "platform": "Magicpin",
    "platformCategory": "food",
    "platformLogo": "🏷️",
    "platformColor": "#E11B22",
    "code": "MAG150",
    "title": "Flat ₹150 off on ₹300+",
    "description": "Save big with this exclusive offer from Magicpin",
    "discountType": "flat",
    "discountValue": 150,
    "maxDiscount": null,
    "minOrderValue": 300,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "sale",
    "verified": true,
    "successRate": 85,
    "lastWorked": "1 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "food",
      "magicpin",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "food",
      "magicpin",
      "mag150",
      "save",
      "deal"
    ],
    "aiScore": 92,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 701
  },
  {
    "id": "c57",
    "platform": "Zepto",
    "platformCategory": "grocery",
    "platformLogo": "⏱️",
    "platformColor": "#3A1847",
    "code": "ZEP300",
    "title": "Flat ₹300 off on ₹600+",
    "description": "Save big with this exclusive offer from Zepto",
    "discountType": "flat",
    "discountValue": 300,
    "maxDiscount": null,
    "minOrderValue": 600,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "coupon",
    "verified": true,
    "successRate": 89,
    "lastWorked": "9 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "grocery",
      "zepto",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "grocery",
      "zepto",
      "zep300",
      "save",
      "deal"
    ],
    "aiScore": 84,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 4068
  },
  {
    "id": "c58",
    "platform": "Goibibo",
    "platformCategory": "travel",
    "platformLogo": "🏨",
    "platformColor": "#2274E0",
    "code": null,
    "title": "35% off up to ₹350",
    "description": "Save big with this exclusive offer from Goibibo",
    "discountType": "percent",
    "discountValue": 35,
    "maxDiscount": 350,
    "minOrderValue": 1750,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bank",
    "verified": true,
    "successRate": 82,
    "lastWorked": "5 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "travel",
      "goibibo",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "travel",
      "goibibo",
      "goi350",
      "save",
      "deal"
    ],
    "aiScore": 97,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 2947
  },
  {
    "id": "c59",
    "platform": "Netmeds",
    "platformCategory": "pharmacy",
    "platformLogo": "🩺",
    "platformColor": "#32AEB1",
    "code": null,
    "title": "Flat ₹250 off on ₹500+",
    "description": "Save big with this exclusive offer from Netmeds",
    "discountType": "flat",
    "discountValue": 250,
    "maxDiscount": null,
    "minOrderValue": 500,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "wallet",
    "verified": true,
    "successRate": 85,
    "lastWorked": "5 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "pharmacy",
      "netmeds",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "pharmacy",
      "netmeds",
      "net250",
      "save",
      "deal"
    ],
    "aiScore": 85,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 2562
  },
  {
    "id": "c60",
    "platform": "Mobikwik",
    "platformCategory": "recharge",
    "platformLogo": "👛",
    "platformColor": "#002970",
    "code": "MOB500",
    "title": "50% off up to ₹500",
    "description": "Save big with this exclusive offer from Mobikwik",
    "discountType": "percent",
    "discountValue": 50,
    "maxDiscount": 500,
    "minOrderValue": 1000,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "cashback",
    "verified": true,
    "successRate": 89,
    "lastWorked": "6 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "recharge",
      "mobikwik",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "recharge",
      "mobikwik",
      "mob500",
      "save",
      "deal"
    ],
    "aiScore": 97,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 2114
  },
  {
    "id": "c61",
    "platform": "Netflix",
    "platformCategory": "ott",
    "platformLogo": "🎬",
    "platformColor": "#E50914",
    "code": "NET150",
    "title": "15% off up to ₹150",
    "description": "Save big with this exclusive offer from Netflix",
    "discountType": "percent",
    "discountValue": 15,
    "maxDiscount": 150,
    "minOrderValue": 900,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "emi",
    "verified": true,
    "successRate": 98,
    "lastWorked": "9 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "ott",
      "netflix",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "ott",
      "netflix",
      "net150",
      "save",
      "deal"
    ],
    "aiScore": 83,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 3162
  },
  {
    "id": "c62",
    "platform": "SBI Card",
    "platformCategory": "bank",
    "platformLogo": "💳",
    "platformColor": "#284FB5",
    "code": "SBI200",
    "title": "20% off up to ₹200",
    "description": "Save big with this exclusive offer from SBI Card",
    "discountType": "percent",
    "discountValue": 20,
    "maxDiscount": 200,
    "minOrderValue": 600,
    "cashback": 0,
    "bankOffer": "SBI Card Credit Card",
    "offerType": "bogo",
    "verified": true,
    "successRate": 95,
    "lastWorked": "8 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "bank",
      "sbi card",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "bank",
      "sbi card",
      "sbi200",
      "save",
      "deal"
    ],
    "aiScore": 91,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 3474
  },
  {
    "id": "c63",
    "platform": "Paytm",
    "platformCategory": "wallet",
    "platformLogo": "💸",
    "platformColor": "#00B9F5",
    "code": "PAY200",
    "title": "20% off up to ₹200",
    "description": "Save big with this exclusive offer from Paytm",
    "discountType": "percent",
    "discountValue": 20,
    "maxDiscount": 200,
    "minOrderValue": 400,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "sale",
    "verified": true,
    "successRate": 92,
    "lastWorked": "1 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "wallet",
      "paytm",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "wallet",
      "paytm",
      "pay200",
      "save",
      "deal"
    ],
    "aiScore": 95,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 5070
  },
  {
    "id": "c64",
    "platform": "AJIO",
    "platformCategory": "shopping",
    "platformLogo": "👗",
    "platformColor": "#2C415C",
    "code": null,
    "title": "30% off up to ₹300",
    "description": "Save big with this exclusive offer from AJIO",
    "discountType": "percent",
    "discountValue": 30,
    "maxDiscount": 300,
    "minOrderValue": 1200,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "coupon",
    "verified": true,
    "successRate": 91,
    "lastWorked": "2 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "shopping",
      "ajio",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "shopping",
      "ajio",
      "aji300",
      "save",
      "deal"
    ],
    "aiScore": 84,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 3678
  },
  {
    "id": "c65",
    "platform": "Swiggy",
    "platformCategory": "food",
    "platformLogo": "🍔",
    "platformColor": "#FC8019",
    "code": "SWI450",
    "title": "Flat ₹450 off on ₹900+",
    "description": "Save big with this exclusive offer from Swiggy",
    "discountType": "flat",
    "discountValue": 450,
    "maxDiscount": null,
    "minOrderValue": 900,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bank",
    "verified": true,
    "successRate": 87,
    "lastWorked": "2 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "food",
      "swiggy",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "food",
      "swiggy",
      "swi450",
      "save",
      "deal"
    ],
    "aiScore": 86,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 4901
  },
  {
    "id": "c66",
    "platform": "Blinkit",
    "platformCategory": "grocery",
    "platformLogo": "⚡",
    "platformColor": "#F8CB46",
    "code": "BLI150",
    "title": "15% off up to ₹150",
    "description": "Save big with this exclusive offer from Blinkit",
    "discountType": "percent",
    "discountValue": 15,
    "maxDiscount": 150,
    "minOrderValue": 600,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "wallet",
    "verified": true,
    "successRate": 87,
    "lastWorked": "8 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "grocery",
      "blinkit",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "grocery",
      "blinkit",
      "bli150",
      "save",
      "deal"
    ],
    "aiScore": 87,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 1780
  },
  {
    "id": "c67",
    "platform": "EaseMyTrip",
    "platformCategory": "travel",
    "platformLogo": "✈️",
    "platformColor": "#2196F3",
    "code": "EAS500",
    "title": "50% off up to ₹500",
    "description": "Save big with this exclusive offer from EaseMyTrip",
    "discountType": "percent",
    "discountValue": 50,
    "maxDiscount": 500,
    "minOrderValue": 2500,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "cashback",
    "verified": true,
    "successRate": 93,
    "lastWorked": "10 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "travel",
      "easemytrip",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "travel",
      "easemytrip",
      "eas500",
      "save",
      "deal"
    ],
    "aiScore": 92,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 1863
  },
  {
    "id": "c68",
    "platform": "Apollo Pharmacy",
    "platformCategory": "pharmacy",
    "platformLogo": "🏥",
    "platformColor": "#005B82",
    "code": "APO250",
    "title": "Flat ₹250 off on ₹500+",
    "description": "Save big with this exclusive offer from Apollo Pharmacy",
    "discountType": "flat",
    "discountValue": 250,
    "maxDiscount": null,
    "minOrderValue": 500,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "emi",
    "verified": true,
    "successRate": 81,
    "lastWorked": "9 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "pharmacy",
      "apollo pharmacy",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "pharmacy",
      "apollo pharmacy",
      "apo250",
      "save",
      "deal"
    ],
    "aiScore": 93,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 4547
  },
  {
    "id": "c69",
    "platform": "Google Pay",
    "platformCategory": "recharge",
    "platformLogo": "💳",
    "platformColor": "#34A853",
    "code": "GOO350",
    "title": "Flat ₹350 off on ₹700+",
    "description": "Save big with this exclusive offer from Google Pay",
    "discountType": "flat",
    "discountValue": 350,
    "maxDiscount": null,
    "minOrderValue": 700,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bogo",
    "verified": true,
    "successRate": 94,
    "lastWorked": "3 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "recharge",
      "google pay",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "recharge",
      "google pay",
      "goo350",
      "save",
      "deal"
    ],
    "aiScore": 83,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 4500
  },
  {
    "id": "c70",
    "platform": "SonyLIV",
    "platformCategory": "ott",
    "platformLogo": "📺",
    "platformColor": "#000000",
    "code": "SON450",
    "title": "Flat ₹450 off on ₹900+",
    "description": "Save big with this exclusive offer from SonyLIV",
    "discountType": "flat",
    "discountValue": 450,
    "maxDiscount": null,
    "minOrderValue": 900,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "sale",
    "verified": true,
    "successRate": 90,
    "lastWorked": "4 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "ott",
      "sonyliv",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "ott",
      "sonyliv",
      "son450",
      "save",
      "deal"
    ],
    "aiScore": 90,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 200
  },
  {
    "id": "c71",
    "platform": "Kotak",
    "platformCategory": "bank",
    "platformLogo": "🏦",
    "platformColor": "#ED1C24",
    "code": "KOT400",
    "title": "Flat ₹400 off on ₹800+",
    "description": "Save big with this exclusive offer from Kotak",
    "discountType": "flat",
    "discountValue": 400,
    "maxDiscount": null,
    "minOrderValue": 800,
    "cashback": 0,
    "bankOffer": "Kotak Credit Card",
    "offerType": "coupon",
    "verified": true,
    "successRate": 93,
    "lastWorked": "10 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "bank",
      "kotak",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "bank",
      "kotak",
      "kot400",
      "save",
      "deal"
    ],
    "aiScore": 95,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 102
  },
  {
    "id": "c72",
    "platform": "Paytm",
    "platformCategory": "wallet",
    "platformLogo": "💸",
    "platformColor": "#00B9F5",
    "code": "PAY250",
    "title": "Flat ₹250 off on ₹500+",
    "description": "Save big with this exclusive offer from Paytm",
    "discountType": "flat",
    "discountValue": 250,
    "maxDiscount": null,
    "minOrderValue": 500,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "bank",
    "verified": true,
    "successRate": 97,
    "lastWorked": "7 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "wallet",
      "paytm",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "wallet",
      "paytm",
      "pay250",
      "save",
      "deal"
    ],
    "aiScore": 96,
    "isAutoApply": true,
    "isExclusive": true,
    "usedCount": 1358
  },
  {
    "id": "c73",
    "platform": "Myntra",
    "platformCategory": "shopping",
    "platformLogo": "👚",
    "platformColor": "#FF3E6C",
    "code": "MYN450",
    "title": "Flat ₹450 off on ₹900+",
    "description": "Save big with this exclusive offer from Myntra",
    "discountType": "flat",
    "discountValue": 450,
    "maxDiscount": null,
    "minOrderValue": 900,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "wallet",
    "verified": true,
    "successRate": 84,
    "lastWorked": "4 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "shopping",
      "myntra",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "shopping",
      "myntra",
      "myn450",
      "save",
      "deal"
    ],
    "aiScore": 94,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 1738
  },
  {
    "id": "c74",
    "platform": "Zomato",
    "platformCategory": "food",
    "platformLogo": "🍕",
    "platformColor": "#E23744",
    "code": "ZOM150",
    "title": "15% off up to ₹150",
    "description": "Save big with this exclusive offer from Zomato",
    "discountType": "percent",
    "discountValue": 15,
    "maxDiscount": 150,
    "minOrderValue": 600,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "cashback",
    "verified": true,
    "successRate": 82,
    "lastWorked": "4 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "food",
      "zomato",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "food",
      "zomato",
      "zom150",
      "save",
      "deal"
    ],
    "aiScore": 94,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 4126
  },
  {
    "id": "c75",
    "platform": "JioMart",
    "platformCategory": "grocery",
    "platformLogo": "🧺",
    "platformColor": "#0088CC",
    "code": "JIO50",
    "title": "Flat ₹50 off on ₹100+",
    "description": "Save big with this exclusive offer from JioMart",
    "discountType": "flat",
    "discountValue": 50,
    "maxDiscount": null,
    "minOrderValue": 100,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "emi",
    "verified": true,
    "successRate": 95,
    "lastWorked": "7 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "grocery",
      "jiomart",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "grocery",
      "jiomart",
      "jio50",
      "save",
      "deal"
    ],
    "aiScore": 85,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 4599
  },
  {
    "id": "c76",
    "platform": "Cleartrip",
    "platformCategory": "travel",
    "platformLogo": "🌍",
    "platformColor": "#F77728",
    "code": "CLE300",
    "title": "30% off up to ₹300",
    "description": "Save big with this exclusive offer from Cleartrip",
    "discountType": "percent",
    "discountValue": 30,
    "maxDiscount": 300,
    "minOrderValue": 1500,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bogo",
    "verified": true,
    "successRate": 92,
    "lastWorked": "4 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "travel",
      "cleartrip",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "travel",
      "cleartrip",
      "cle300",
      "save",
      "deal"
    ],
    "aiScore": 83,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 4089
  },
  {
    "id": "c77",
    "platform": "Tata 1mg",
    "platformCategory": "pharmacy",
    "platformLogo": "💊",
    "platformColor": "#FF6F61",
    "code": "TAT300",
    "title": "30% off up to ₹300",
    "description": "Save big with this exclusive offer from Tata 1mg",
    "discountType": "percent",
    "discountValue": 30,
    "maxDiscount": 300,
    "minOrderValue": 900,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "sale",
    "verified": true,
    "successRate": 81,
    "lastWorked": "1 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "pharmacy",
      "tata 1mg",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "pharmacy",
      "tata 1mg",
      "tat300",
      "save",
      "deal"
    ],
    "aiScore": 84,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 3913
  },
  {
    "id": "c78",
    "platform": "Mobikwik",
    "platformCategory": "recharge",
    "platformLogo": "👛",
    "platformColor": "#002970",
    "code": "MOB200",
    "title": "Flat ₹200 off on ₹400+",
    "description": "Save big with this exclusive offer from Mobikwik",
    "discountType": "flat",
    "discountValue": 200,
    "maxDiscount": null,
    "minOrderValue": 400,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "coupon",
    "verified": true,
    "successRate": 94,
    "lastWorked": "7 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "recharge",
      "mobikwik",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "recharge",
      "mobikwik",
      "mob200",
      "save",
      "deal"
    ],
    "aiScore": 87,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 4475
  },
  {
    "id": "c79",
    "platform": "Netflix",
    "platformCategory": "ott",
    "platformLogo": "🎬",
    "platformColor": "#E50914",
    "code": "NET300",
    "title": "30% off up to ₹300",
    "description": "Save big with this exclusive offer from Netflix",
    "discountType": "percent",
    "discountValue": 30,
    "maxDiscount": 300,
    "minOrderValue": 1200,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "bank",
    "verified": true,
    "successRate": 86,
    "lastWorked": "8 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "ott",
      "netflix",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "ott",
      "netflix",
      "net300",
      "save",
      "deal"
    ],
    "aiScore": 98,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 3130
  },
  {
    "id": "c80",
    "platform": "SBI Card",
    "platformCategory": "bank",
    "platformLogo": "💳",
    "platformColor": "#284FB5",
    "code": "SBI300",
    "title": "Flat ₹300 off on ₹600+",
    "description": "Save big with this exclusive offer from SBI Card",
    "discountType": "flat",
    "discountValue": 300,
    "maxDiscount": null,
    "minOrderValue": 600,
    "cashback": 0,
    "bankOffer": "SBI Card Credit Card",
    "offerType": "wallet",
    "verified": true,
    "successRate": 83,
    "lastWorked": "9 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "bank",
      "sbi card",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "bank",
      "sbi card",
      "sbi300",
      "save",
      "deal"
    ],
    "aiScore": 98,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 2940
  },
  {
    "id": "c81",
    "platform": "Paytm",
    "platformCategory": "wallet",
    "platformLogo": "💸",
    "platformColor": "#00B9F5",
    "code": "PAY100",
    "title": "Flat ₹100 off on ₹200+",
    "description": "Save big with this exclusive offer from Paytm",
    "discountType": "flat",
    "discountValue": 100,
    "maxDiscount": null,
    "minOrderValue": 200,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "cashback",
    "verified": true,
    "successRate": 85,
    "lastWorked": "1 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "wallet",
      "paytm",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "wallet",
      "paytm",
      "pay100",
      "save",
      "deal"
    ],
    "aiScore": 96,
    "isAutoApply": true,
    "isExclusive": true,
    "usedCount": 2568
  },
  {
    "id": "c82",
    "platform": "Flipkart",
    "platformCategory": "shopping",
    "platformLogo": "🛍️",
    "platformColor": "#2874F0",
    "code": null,
    "title": "Flat ₹250 off on ₹500+",
    "description": "Save big with this exclusive offer from Flipkart",
    "discountType": "flat",
    "discountValue": 250,
    "maxDiscount": null,
    "minOrderValue": 500,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "emi",
    "verified": true,
    "successRate": 93,
    "lastWorked": "9 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "shopping",
      "flipkart",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "shopping",
      "flipkart",
      "fli250",
      "save",
      "deal"
    ],
    "aiScore": 95,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 4300
  },
  {
    "id": "c83",
    "platform": "Dominos",
    "platformCategory": "food",
    "platformLogo": "🍕",
    "platformColor": "#0055A5",
    "code": "DOM300",
    "title": "30% off up to ₹300",
    "description": "Save big with this exclusive offer from Dominos",
    "discountType": "percent",
    "discountValue": 30,
    "maxDiscount": 300,
    "minOrderValue": 1800,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bogo",
    "verified": true,
    "successRate": 94,
    "lastWorked": "1 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "food",
      "dominos",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "food",
      "dominos",
      "dom300",
      "save",
      "deal"
    ],
    "aiScore": 80,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 738
  },
  {
    "id": "c84",
    "platform": "Instamart",
    "platformCategory": "grocery",
    "platformLogo": "🥑",
    "platformColor": "#FC8019",
    "code": "INS150",
    "title": "Flat ₹150 off on ₹300+",
    "description": "Save big with this exclusive offer from Instamart",
    "discountType": "flat",
    "discountValue": 150,
    "maxDiscount": null,
    "minOrderValue": 300,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "sale",
    "verified": true,
    "successRate": 92,
    "lastWorked": "1 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "grocery",
      "instamart",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "grocery",
      "instamart",
      "ins150",
      "save",
      "deal"
    ],
    "aiScore": 94,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 567
  },
  {
    "id": "c85",
    "platform": "OYO",
    "platformCategory": "travel",
    "platformLogo": "🏨",
    "platformColor": "#EE2A24",
    "code": "OYO50",
    "title": "Flat ₹50 off on ₹100+",
    "description": "Save big with this exclusive offer from OYO",
    "discountType": "flat",
    "discountValue": 50,
    "maxDiscount": null,
    "minOrderValue": 100,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "coupon",
    "verified": true,
    "successRate": 88,
    "lastWorked": "7 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "travel",
      "oyo",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "travel",
      "oyo",
      "oyo50",
      "save",
      "deal"
    ],
    "aiScore": 95,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 476
  },
  {
    "id": "c86",
    "platform": "PharmEasy",
    "platformCategory": "pharmacy",
    "platformLogo": "⚕️",
    "platformColor": "#10847E",
    "code": "PHA50",
    "title": "Flat ₹50 off on ₹100+",
    "description": "Save big with this exclusive offer from PharmEasy",
    "discountType": "flat",
    "discountValue": 50,
    "maxDiscount": null,
    "minOrderValue": 100,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "bank",
    "verified": true,
    "successRate": 82,
    "lastWorked": "5 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "pharmacy",
      "pharmeasy",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "pharmacy",
      "pharmeasy",
      "pha50",
      "save",
      "deal"
    ],
    "aiScore": 90,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 2480
  },
  {
    "id": "c87",
    "platform": "Google Pay",
    "platformCategory": "recharge",
    "platformLogo": "💳",
    "platformColor": "#34A853",
    "code": null,
    "title": "Flat ₹300 off on ₹600+",
    "description": "Save big with this exclusive offer from Google Pay",
    "discountType": "flat",
    "discountValue": 300,
    "maxDiscount": null,
    "minOrderValue": 600,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "wallet",
    "verified": true,
    "successRate": 82,
    "lastWorked": "10 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "recharge",
      "google pay",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "recharge",
      "google pay",
      "goo300",
      "save",
      "deal"
    ],
    "aiScore": 86,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 1073
  },
  {
    "id": "c88",
    "platform": "SonyLIV",
    "platformCategory": "ott",
    "platformLogo": "📺",
    "platformColor": "#000000",
    "code": "SON400",
    "title": "Flat ₹400 off on ₹800+",
    "description": "Save big with this exclusive offer from SonyLIV",
    "discountType": "flat",
    "discountValue": 400,
    "maxDiscount": null,
    "minOrderValue": 800,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "cashback",
    "verified": true,
    "successRate": 93,
    "lastWorked": "10 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "ott",
      "sonyliv",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "ott",
      "sonyliv",
      "son400",
      "save",
      "deal"
    ],
    "aiScore": 98,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 3935
  },
  {
    "id": "c89",
    "platform": "Kotak",
    "platformCategory": "bank",
    "platformLogo": "🏦",
    "platformColor": "#ED1C24",
    "code": "KOT300",
    "title": "Flat ₹300 off on ₹600+",
    "description": "Save big with this exclusive offer from Kotak",
    "discountType": "flat",
    "discountValue": 300,
    "maxDiscount": null,
    "minOrderValue": 600,
    "cashback": 0,
    "bankOffer": "Kotak Credit Card",
    "offerType": "emi",
    "verified": true,
    "successRate": 96,
    "lastWorked": "1 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "bank",
      "kotak",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "bank",
      "kotak",
      "kot300",
      "save",
      "deal"
    ],
    "aiScore": 87,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 1855
  },
  {
    "id": "c90",
    "platform": "Paytm",
    "platformCategory": "wallet",
    "platformLogo": "💸",
    "platformColor": "#00B9F5",
    "code": null,
    "title": "5% off up to ₹50",
    "description": "Save big with this exclusive offer from Paytm",
    "discountType": "percent",
    "discountValue": 5,
    "maxDiscount": 50,
    "minOrderValue": 250,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bogo",
    "verified": true,
    "successRate": 96,
    "lastWorked": "3 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "wallet",
      "paytm",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "wallet",
      "paytm",
      "pay50",
      "save",
      "deal"
    ],
    "aiScore": 92,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 2277
  },
  {
    "id": "c91",
    "platform": "Amazon",
    "platformCategory": "shopping",
    "platformLogo": "🛒",
    "platformColor": "#FF9900",
    "code": null,
    "title": "Flat ₹400 off on ₹800+",
    "description": "Save big with this exclusive offer from Amazon",
    "discountType": "flat",
    "discountValue": 400,
    "maxDiscount": null,
    "minOrderValue": 800,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "sale",
    "verified": true,
    "successRate": 82,
    "lastWorked": "5 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "shopping",
      "amazon",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "shopping",
      "amazon",
      "ama400",
      "save",
      "deal"
    ],
    "aiScore": 94,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 651
  },
  {
    "id": "c92",
    "platform": "Pizza Hut",
    "platformCategory": "food",
    "platformLogo": "🍕",
    "platformColor": "#C8102E",
    "code": "PIZ250",
    "title": "Flat ₹250 off on ₹500+",
    "description": "Save big with this exclusive offer from Pizza Hut",
    "discountType": "flat",
    "discountValue": 250,
    "maxDiscount": null,
    "minOrderValue": 500,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "coupon",
    "verified": true,
    "successRate": 87,
    "lastWorked": "2 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "food",
      "pizza hut",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "food",
      "pizza hut",
      "piz250",
      "save",
      "deal"
    ],
    "aiScore": 81,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 522
  },
  {
    "id": "c93",
    "platform": "BigBasket",
    "platformCategory": "grocery",
    "platformLogo": "🛒",
    "platformColor": "#84C225",
    "code": null,
    "title": "50% off up to ₹500",
    "description": "Save big with this exclusive offer from BigBasket",
    "discountType": "percent",
    "discountValue": 50,
    "maxDiscount": 500,
    "minOrderValue": 2000,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bank",
    "verified": true,
    "successRate": 99,
    "lastWorked": "10 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "grocery",
      "bigbasket",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "grocery",
      "bigbasket",
      "big500",
      "save",
      "deal"
    ],
    "aiScore": 98,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 563
  },
  {
    "id": "c94",
    "platform": "Agoda",
    "platformCategory": "travel",
    "platformLogo": "🗺️",
    "platformColor": "#5B99C2",
    "code": "AGO400",
    "title": "Flat ₹400 off on ₹800+",
    "description": "Save big with this exclusive offer from Agoda",
    "discountType": "flat",
    "discountValue": 400,
    "maxDiscount": null,
    "minOrderValue": 800,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "wallet",
    "verified": true,
    "successRate": 93,
    "lastWorked": "10 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "travel",
      "agoda",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "travel",
      "agoda",
      "ago400",
      "save",
      "deal"
    ],
    "aiScore": 92,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 1105
  },
  {
    "id": "c95",
    "platform": "Netmeds",
    "platformCategory": "pharmacy",
    "platformLogo": "🩺",
    "platformColor": "#32AEB1",
    "code": "NET350",
    "title": "35% off up to ₹350",
    "description": "Save big with this exclusive offer from Netmeds",
    "discountType": "percent",
    "discountValue": 35,
    "maxDiscount": 350,
    "minOrderValue": 1750,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "cashback",
    "verified": true,
    "successRate": 89,
    "lastWorked": "8 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "pharmacy",
      "netmeds",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "pharmacy",
      "netmeds",
      "net350",
      "save",
      "deal"
    ],
    "aiScore": 84,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 1109
  },
  {
    "id": "c96",
    "platform": "Mobikwik",
    "platformCategory": "recharge",
    "platformLogo": "👛",
    "platformColor": "#002970",
    "code": null,
    "title": "Flat ₹50 off on ₹100+",
    "description": "Save big with this exclusive offer from Mobikwik",
    "discountType": "flat",
    "discountValue": 50,
    "maxDiscount": null,
    "minOrderValue": 100,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "emi",
    "verified": true,
    "successRate": 82,
    "lastWorked": "8 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "recharge",
      "mobikwik",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "recharge",
      "mobikwik",
      "mob50",
      "save",
      "deal"
    ],
    "aiScore": 94,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 2186
  },
  {
    "id": "c97",
    "platform": "Netflix",
    "platformCategory": "ott",
    "platformLogo": "🎬",
    "platformColor": "#E50914",
    "code": "NET50",
    "title": "5% off up to ₹50",
    "description": "Save big with this exclusive offer from Netflix",
    "discountType": "percent",
    "discountValue": 5,
    "maxDiscount": 50,
    "minOrderValue": 100,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bogo",
    "verified": true,
    "successRate": 97,
    "lastWorked": "5 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "ott",
      "netflix",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "ott",
      "netflix",
      "net50",
      "save",
      "deal"
    ],
    "aiScore": 86,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 3880
  },
  {
    "id": "c98",
    "platform": "SBI Card",
    "platformCategory": "bank",
    "platformLogo": "💳",
    "platformColor": "#284FB5",
    "code": "SBI300",
    "title": "Flat ₹300 off on ₹600+",
    "description": "Save big with this exclusive offer from SBI Card",
    "discountType": "flat",
    "discountValue": 300,
    "maxDiscount": null,
    "minOrderValue": 600,
    "cashback": 0,
    "bankOffer": "SBI Card Credit Card",
    "offerType": "sale",
    "verified": true,
    "successRate": 98,
    "lastWorked": "9 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "bank",
      "sbi card",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "bank",
      "sbi card",
      "sbi300",
      "save",
      "deal"
    ],
    "aiScore": 83,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 126
  },
  {
    "id": "c99",
    "platform": "Paytm",
    "platformCategory": "wallet",
    "platformLogo": "💸",
    "platformColor": "#00B9F5",
    "code": "PAY350",
    "title": "35% off up to ₹350",
    "description": "Save big with this exclusive offer from Paytm",
    "discountType": "percent",
    "discountValue": 35,
    "maxDiscount": 350,
    "minOrderValue": 1050,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "coupon",
    "verified": true,
    "successRate": 95,
    "lastWorked": "5 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "wallet",
      "paytm",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "wallet",
      "paytm",
      "pay350",
      "save",
      "deal"
    ],
    "aiScore": 93,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 3108
  },
  {
    "id": "c100",
    "platform": "FirstCry",
    "platformCategory": "shopping",
    "platformLogo": "👶",
    "platformColor": "#FF7043",
    "code": null,
    "title": "Flat ₹50 off on ₹100+",
    "description": "Save big with this exclusive offer from FirstCry",
    "discountType": "flat",
    "discountValue": 50,
    "maxDiscount": null,
    "minOrderValue": 100,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "bank",
    "verified": true,
    "successRate": 86,
    "lastWorked": "5 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "shopping",
      "firstcry",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "shopping",
      "firstcry",
      "fir50",
      "save",
      "deal"
    ],
    "aiScore": 92,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 1485
  },
  {
    "id": "c101",
    "platform": "McDonalds",
    "platformCategory": "food",
    "platformLogo": "🍟",
    "platformColor": "#FFC72C",
    "code": "MCD50",
    "title": "5% off up to ₹50",
    "description": "Save big with this exclusive offer from McDonalds",
    "discountType": "percent",
    "discountValue": 5,
    "maxDiscount": 50,
    "minOrderValue": 300,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "wallet",
    "verified": true,
    "successRate": 87,
    "lastWorked": "8 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "food",
      "mcdonalds",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "food",
      "mcdonalds",
      "mcd50",
      "save",
      "deal"
    ],
    "aiScore": 80,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 4923
  },
  {
    "id": "c102",
    "platform": "Zepto",
    "platformCategory": "grocery",
    "platformLogo": "⏱️",
    "platformColor": "#3A1847",
    "code": null,
    "title": "Flat ₹50 off on ₹100+",
    "description": "Save big with this exclusive offer from Zepto",
    "discountType": "flat",
    "discountValue": 50,
    "maxDiscount": null,
    "minOrderValue": 100,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "cashback",
    "verified": true,
    "successRate": 92,
    "lastWorked": "4 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "grocery",
      "zepto",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "grocery",
      "zepto",
      "zep50",
      "save",
      "deal"
    ],
    "aiScore": 89,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 3657
  },
  {
    "id": "c103",
    "platform": "ixigo",
    "platformCategory": "travel",
    "platformLogo": "🚆",
    "platformColor": "#2F1F83",
    "code": "IXI400",
    "title": "Flat ₹400 off on ₹800+",
    "description": "Save big with this exclusive offer from ixigo",
    "discountType": "flat",
    "discountValue": 400,
    "maxDiscount": null,
    "minOrderValue": 800,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "emi",
    "verified": true,
    "successRate": 95,
    "lastWorked": "2 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "travel",
      "ixigo",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "travel",
      "ixigo",
      "ixi400",
      "save",
      "deal"
    ],
    "aiScore": 81,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 3399
  },
  {
    "id": "c104",
    "platform": "Apollo Pharmacy",
    "platformCategory": "pharmacy",
    "platformLogo": "🏥",
    "platformColor": "#005B82",
    "code": "APO200",
    "title": "20% off up to ₹200",
    "description": "Save big with this exclusive offer from Apollo Pharmacy",
    "discountType": "percent",
    "discountValue": 20,
    "maxDiscount": 200,
    "minOrderValue": 1200,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "bogo",
    "verified": true,
    "successRate": 92,
    "lastWorked": "5 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "pharmacy",
      "apollo pharmacy",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "pharmacy",
      "apollo pharmacy",
      "apo200",
      "save",
      "deal"
    ],
    "aiScore": 89,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 4238
  },
  {
    "id": "c105",
    "platform": "Google Pay",
    "platformCategory": "recharge",
    "platformLogo": "💳",
    "platformColor": "#34A853",
    "code": null,
    "title": "Flat ₹50 off on ₹100+",
    "description": "Save big with this exclusive offer from Google Pay",
    "discountType": "flat",
    "discountValue": 50,
    "maxDiscount": null,
    "minOrderValue": 100,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "sale",
    "verified": true,
    "successRate": 96,
    "lastWorked": "6 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "recharge",
      "google pay",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "recharge",
      "google pay",
      "goo50",
      "save",
      "deal"
    ],
    "aiScore": 94,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 2968
  },
  {
    "id": "c106",
    "platform": "SonyLIV",
    "platformCategory": "ott",
    "platformLogo": "📺",
    "platformColor": "#000000",
    "code": "SON100",
    "title": "Flat ₹100 off on ₹200+",
    "description": "Save big with this exclusive offer from SonyLIV",
    "discountType": "flat",
    "discountValue": 100,
    "maxDiscount": null,
    "minOrderValue": 200,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "coupon",
    "verified": true,
    "successRate": 83,
    "lastWorked": "8 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "ott",
      "sonyliv",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "ott",
      "sonyliv",
      "son100",
      "save",
      "deal"
    ],
    "aiScore": 97,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 3599
  },
  {
    "id": "c107",
    "platform": "Kotak",
    "platformCategory": "bank",
    "platformLogo": "🏦",
    "platformColor": "#ED1C24",
    "code": "KOT300",
    "title": "30% off up to ₹300",
    "description": "Save big with this exclusive offer from Kotak",
    "discountType": "percent",
    "discountValue": 30,
    "maxDiscount": 300,
    "minOrderValue": 1800,
    "cashback": 0,
    "bankOffer": "Kotak Credit Card",
    "offerType": "bank",
    "verified": true,
    "successRate": 88,
    "lastWorked": "9 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "bank",
      "kotak",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "bank",
      "kotak",
      "kot300",
      "save",
      "deal"
    ],
    "aiScore": 80,
    "isAutoApply": false,
    "isExclusive": true,
    "usedCount": 4629
  },
  {
    "id": "c108",
    "platform": "Paytm",
    "platformCategory": "wallet",
    "platformLogo": "💸",
    "platformColor": "#00B9F5",
    "code": "PAY500",
    "title": "50% off up to ₹500",
    "description": "Save big with this exclusive offer from Paytm",
    "discountType": "percent",
    "discountValue": 50,
    "maxDiscount": 500,
    "minOrderValue": 2500,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "wallet",
    "verified": true,
    "successRate": 95,
    "lastWorked": "4 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "wallet",
      "paytm",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "wallet",
      "paytm",
      "pay500",
      "save",
      "deal"
    ],
    "aiScore": 99,
    "isAutoApply": false,
    "isExclusive": false,
    "usedCount": 1144
  },
  {
    "id": "c109",
    "platform": "Croma",
    "platformCategory": "shopping",
    "platformLogo": "🔌",
    "platformColor": "#00E9C5",
    "code": null,
    "title": "30% off up to ₹300",
    "description": "Save big with this exclusive offer from Croma",
    "discountType": "percent",
    "discountValue": 30,
    "maxDiscount": 300,
    "minOrderValue": 1500,
    "cashback": 0,
    "bankOffer": "HDFC Credit Card",
    "offerType": "cashback",
    "verified": true,
    "successRate": 82,
    "lastWorked": "3 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "shopping",
      "croma",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "shopping",
      "croma",
      "cro300",
      "save",
      "deal"
    ],
    "aiScore": 80,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 4999
  },
  {
    "id": "c110",
    "platform": "KFC",
    "platformCategory": "food",
    "platformLogo": "🍗",
    "platformColor": "#E4002B",
    "code": "KFC300",
    "title": "30% off up to ₹300",
    "description": "Save big with this exclusive offer from KFC",
    "discountType": "percent",
    "discountValue": 30,
    "maxDiscount": 300,
    "minOrderValue": 1200,
    "cashback": 0,
    "bankOffer": null,
    "offerType": "emi",
    "verified": true,
    "successRate": 89,
    "lastWorked": "1 hours ago",
    "expiresAt": "2026-12-31T23:59:59Z",
    "isExpired": false,
    "tags": [
      "food",
      "kfc",
      "discount",
      "offer"
    ],
    "searchKeywords": [
      "food",
      "kfc",
      "kfc300",
      "save",
      "deal"
    ],
    "aiScore": 87,
    "isAutoApply": true,
    "isExclusive": false,
    "usedCount": 3465
  }
];

export const searchCoupons = (query, category = 'all') => {
  let filtered = allCoupons;
  if (category !== 'all') {
    filtered = filtered.filter((c) => c.platformCategory === category);
  }
  if (query) {
    const q = query.toLowerCase();
    filtered = filtered.filter(
      (c) =>
        c.platform.toLowerCase().includes(q) ||
        c.title.toLowerCase().includes(q) ||
        (c.code && c.code.toLowerCase().includes(q)) ||
        c.searchKeywords.some((k) => k.toLowerCase().includes(q)) ||
        c.tags.some((t) => t.toLowerCase().includes(q))
    );
  }
  return filtered.sort((a, b) => b.aiScore - a.aiScore);
};

export const getBestDeals = (category = 'all', limit = 6) => {
  let filtered = allCoupons.filter((c) => c.verified && !c.isExpired);
  if (category !== 'all') {
    filtered = filtered.filter((c) => c.platformCategory === category);
  }
  return filtered.sort((a, b) => b.aiScore - a.aiScore).slice(0, limit);
};

export const calculatePriceBreakdown = (originalPrice, selectedCoupons) => {
  let couponDiscount = 0;
  let bankDiscount = 0;
  let cashback = 0;
  let walletBonus = 0;

  selectedCoupons.forEach((coupon) => {
    if (coupon.minOrderValue && originalPrice < coupon.minOrderValue) return;

    let discount = 0;
    if (coupon.discountType === 'flat') {
      discount = coupon.discountValue;
    } else if (coupon.discountType === 'percent') {
      discount = (originalPrice * coupon.discountValue) / 100;
    }

    if (coupon.maxDiscount) {
      discount = Math.min(discount, coupon.maxDiscount);
    }

    if (coupon.offerType === 'bank' || coupon.bankOffer) {
      bankDiscount += discount;
    } else if (coupon.offerType === 'wallet') {
      walletBonus += coupon.cashback || discount;
    } else if (coupon.offerType === 'cashback') {
      cashback += coupon.cashback || discount;
    } else {
      couponDiscount += discount;
    }

    if (coupon.cashback && coupon.offerType !== 'cashback' && coupon.offerType !== 'wallet') {
      cashback += coupon.cashback;
    }
  });

  const totalDiscount = couponDiscount + bankDiscount;
  const finalPrice = Math.max(0, originalPrice - totalDiscount);
  const totalSavings = totalDiscount + cashback + walletBonus;
  const savingsPercent = originalPrice > 0 ? ((totalSavings / originalPrice) * 100).toFixed(2) : 0;

  return {
    originalPrice,
    couponDiscount,
    bankDiscount,
    cashback,
    walletBonus,
    finalPrice,
    totalSavings,
    savingsPercent: parseFloat(savingsPercent),
  };
};

export const getCategoryCoupons = (category) => {
  return allCoupons
    .filter((c) => !c.isExpired && c.platformCategory === category)
    .sort((a, b) => b.aiScore - a.aiScore);
};
